### ISSUE TITLE
Infinity

### ISSUE THREAD

**Issue by CP280** [CancerRxGene/gdsctools#158]
Hi Thomas,
I have tested **v 0.16.2**, and I did check your fix rounding to zero negative signed-effects (NA values solved) , but I still have issues with the infinity numbers when producing volcano plots (which whould be fixed in 16.2).

See below.
Thank you!

_pip search gdsctools
gdsctools (0.16.2)  - Set of tools and pipelines to analyse GDSC data (cancerrxgene.org)
  INSTALLED: 0.16.2 (latest)_

volcano.py:542: RuntimeWarning: divide by zero encountered in log10
  self.data['log10pvalue'] = -log10(self.data['pvalue'])
openning html_gdsc_anova/index.html
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-21-127e884bb564> in <module>()
----> 1 report.create_html_pages()

anova_report.pyc in create_html_pages(self, onweb)
    584         """Create all HTML pages"""
    585         self.create_html_main(onweb=onweb)
--> 586         self.create_html_manova(onweb=False)
    587         self.create_html_drugs()
    588         self.create_html_features()

anova_report.pyc in create_html_manova(self, onweb)
    578         """
    579         df = self.get_significant_set()
--> 580         page = HTMLPageMANOVA(self, df, self.company)
    581         page.create_report(onweb)
    582

anova_report.pyc in __init__(self, report, df, company)
    621                 template_filename='manova.html', init_report=False)
    622
--> 623         html = ANOVAResults(df).get_html_table(collapse_table=False)
    624
    625         self.jinja['manova'] = html

anova_results.pyc in get_html_table(self, collapse_table, clip_threshold, index, header, escape)
    339                 'FEATURE_pos_Glass_delta']:
    340             html.add_bgcolor(this, cmap_clip, mode='clip',
--> 341                     threshold=clip_threshold)
    342
    343         # normalise data and annotate with color

htmltable.pyc in add_bgcolor(self, colname, cmap, mode, threshold)
    167         # so pandas will not use the precision for those cases:
    168         data = [easydev.precision(x, self.pd_options['precision'])
--> 169                 for x in data]
    170         html_formatter = '<p style="background-color:{0}">{1}</p>'
    171         self.df[colname] = [html_formatter.format(x, y)

tools.pyc in precision(data, digit)
     39
     40     """
---> 41     data = int(data*pow(10, digit))
     42     data /= pow(10., digit)
     43     return data

OverflowError: cannot convert float infinity to integer

**Comment by cokelaer** [comment]
Hi, one quick solution is as follows.

The issue here is that you have infinite values in the results dataframe. THis is a bug but while the code is fixed, you may set the infinite values to zero and create the report again. It may work.

import numpy as np
results.df = results.df.replace({np.inf:0, -np.inf:0})

**Comment by cokelaer** [comment]
Please have a go with version 0.16.3 thanks

**Comment by CP280** [comment]
Hi Thomas.
I have tried 0.16.3 first, and the problem persists. Then I did set all the ifinite numbers in resuts to 0, and it did fail again creating the individual association files (color cells). Please see attached file.
Thank you.
[error_0.16.3.txt](https://github.com/CancerRxGene/gdsctools/files/616425/error_0.16.3.txt)
